"""Scenario Agent: three coherent futures, and how much weight each deserves.

Specified by docs/pipeline.md. Prompt: prompts/scenario.md.
Owns ResearchState sections: scenarios, sp500_comparison.

PROPOSES, NEVER DECIDES. It supplies bear/base/bull inputs (revenue CAGR, terminal margin, exit
multiple), a REQUESTED weight per case with the reason for it, and one requested tilt to the
base-rate prior. It never states P(beat S&P), a score, a price target or an expected return:
`calc.evaluate_scenarios` computes those, clamps every weight into its band and caps the prior.

`eps_at_horizon` is deliberately left `unavailable` (with its lineage): it is arithmetic of
revenue, margin and share count, and no agent - and no P3 code - does arithmetic. calc derives it.
(docs/requests/2026-09-20-p3-to-p2-step5-calc-contract.md asks P2 to confirm.)

The model writes claims only into `scenarios`. `sp500_comparison` (and the price-target claims) are
generated by the Coordinator from calc's result, so they can never disagree with it.
"""

from __future__ import annotations

from typing import Any

from agents.nested import NestedAgent
from schema.contracts.enums import AgentName
from schema.contracts.scenarios import Scenarios

CASES = ("bear", "base", "bull")
SOURCE = "src:llm:scenario"
_EVIDENCE = {
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": False,
        "properties": {"quote": {"type": "string"}, "source_id": {"type": "string"}},
        "required": ["quote", "source_id"],
    },
}
_CASE_FIELDS = {
    "probability": {"type": "number"},
    "probability_rationale": {"type": "string"},
    "horizon_years": {"type": "integer"},
    "revenue_cagr": {"type": "number"},
    "terminal_margin": {"type": "number"},
    "exit_multiple": {"type": "number"},
    "rationale": {"type": "string"},
    "evidence": _EVIDENCE,
}
_CASE = {
    "type": "object",
    "additionalProperties": False,
    "properties": _CASE_FIELDS,
    "required": list(_CASE_FIELDS),
}


def _assumption(value: float, unit: str) -> dict[str, Any]:
    return {
        "value": float(value),
        "unit": unit,
        "type": "assumption",
        "status": "ok",
        "source_id": SOURCE,
    }


class ScenarioAgent(NestedAgent):
    """Bear/base/bull proposal with reasons for each weight."""

    name = AgentName.SCENARIO
    prompt_file = "scenario.md"
    tools = ("calculate_valuation", "get_financial_facts", "get_filing_section", "resolve_fact")
    items = ("mdna", "business", "risk_factors")
    writable = ("scenarios",)

    def extra_blocks(self, context: dict) -> str:
        """The valuation reading it builds on (it runs after the Valuation Agent)."""
        return "\n\n## UPSTREAM FINDINGS (untrusted data)\n" + self._fenced(
            "upstream:findings", context.get("upstream_text", "")
        )

    def extras_schema(self) -> dict[str, dict]:
        return {
            "scenarios": {
                "type": "object",
                "additionalProperties": False,
                "properties": dict.fromkeys(CASES, _CASE),
                "required": list(CASES),
            },
            "prior_shift": {
                "type": "object",
                "additionalProperties": False,
                "properties": {"value": {"type": "number"}, "reason": {"type": "string"}},
                "required": ["value", "reason"],
            },
        }

    def extras_format(self) -> str:
        return (
            '"scenarios": {"bear": <CASE>, "base": <CASE>, "bull": <CASE>}, '
            '"prior_shift": {"value": <number between -0.15 and 0.15, 0 for none>, "reason": "<why>"}} '
            "where <CASE> = {probability (a fraction; the three must sum to exactly 1.0), "
            "probability_rationale (why THIS weight, naming evidence), horizon_years, "
            "revenue_cagr and terminal_margin (FRACTIONS: 0.08 means 8%), exit_multiple (a P/E, e.g. 22), "
            "rationale, evidence: [{quote, source_id}]}. Do NOT supply eps_at_horizon, a price target, a "
            "return, a probability of beating the index or a score: calc computes those. "
            "The `analysis` findings are for `scenarios` only, and must not contain numerals"
        )

    def build_extras(self, raw: dict, context: dict) -> dict[str, Any]:
        problems: list[str] = []
        cases = raw["scenarios"]
        total = sum(float(cases[c]["probability"]) for c in CASES)
        if abs(total - 1.0) > 1e-6:
            problems.append(f"scenario weights sum to {total:.4f}; they must sum to exactly 1.0")
        built: dict[str, Any] = {}
        for c in CASES:
            s = cases[c]
            if not str(s["rationale"]).strip() or not str(s["probability_rationale"]).strip():
                problems.append(f"{c}: rationale and probability_rationale must not be empty")
            for key, lo, hi, hint in (
                ("revenue_cagr", -0.5, 1.0, "a fraction, e.g. 0.08 for 8%"),
                ("terminal_margin", -1.0, 1.0, "a fraction, e.g. 0.125 for 12.5%"),
                ("exit_multiple", 0.0, 200.0, "a P/E multiple, e.g. 22"),
            ):
                if not lo <= float(s[key]) <= hi:
                    problems.append(f"{c}.{key}={s[key]} is implausible; use {hint}")
            if not 1 <= int(s["horizon_years"]) <= 10:
                problems.append(f"{c}.horizon_years must be between 1 and 10")
            built[c] = {
                "probability": float(s["probability"]),
                "probability_rationale": s["probability_rationale"],
                "horizon_years": int(s["horizon_years"]),
                "revenue_cagr": _assumption(s["revenue_cagr"], "fraction"),
                "terminal_margin": _assumption(s["terminal_margin"], "fraction"),
                "exit_multiple": _assumption(s["exit_multiple"], "multiple"),
                "eps_at_horizon": {  # arithmetic: calc derives it (this agent and P3 do not compute)
                    "value": None,
                    "unit": "usd_per_share",
                    "type": "estimate",
                    "status": "unavailable",
                    "source_id": None,
                    "derived_from": [
                        f"scenarios.{c}.revenue_cagr",
                        f"scenarios.{c}.terminal_margin",
                        "market.shares_outstanding",
                    ],
                },
                "rationale": s["rationale"],
                "evidence": self._verified_evidence(s.get("evidence"), f"scenario.{c}"),
            }
        shift = raw["prior_shift"]
        if not -1.0 <= float(shift["value"]) <= 1.0 or (
            float(shift["value"]) != 0 and not str(shift["reason"]).strip()
        ):
            problems.append("prior_shift needs a value in [-1, 1] and, if not zero, a reason")
        if problems:
            raise ValueError("\n".join(problems))
        proposal = Scenarios.model_validate(
            {
                "schema_version": "2.0.0",
                "ticker": context["ticker"],
                "as_of": context["as_of"],
                "scenarios": built,
                "prior_shift": {
                    "value": float(shift["value"]),
                    "reason": shift["reason"].strip() or "no shift requested",
                    "source": "scenario",
                },
            }
        )
        return {"scenarios_proposal": proposal.model_dump(mode="json")}
